"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'th' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  th: {
    'nav.home': 'หน้าแรก',
    'nav.researchers': 'นักวิจัย',
    'nav.news': 'ข่าวสาร',
    'nav.contact': 'ติดต่อเรา',
    'nav.admin': 'เข้าสู่ระบบ Admin',
    'hero.title': 'นวัตกรรม. วิจัย. ค้นพบ.',
    'hero.subtitle': 'ยินดีต้อนรับสู่กลุ่มวิจัย AIO LAB แห่งมหาวิทยาลัยอุบลราชธานี เรามุ่งมั่นพัฒนางานวิจัยและนวัตกรรมใหม่ๆ เพื่อต่อยอดองค์ความรู้ทางวิทยาศาสตร์และเทคโนโลยีสู่สังคม',
    'hero.btn.researchers': 'รู้จักกับนักวิจัยของเรา',
    'hero.btn.news': 'ข่าวสารและกิจกรรม',
    'researchers.title': 'นักวิจัยของเรา',
    'researchers.subtitle': 'ทำความรู้จักกับบุคลากรและทีมนักวิจัยแห่ง AIO LAB มหาวิทยาลัยอุบลราชธานี',
    'researchers.loading': 'กำลังโหลดข้อมูล...',
    'researchers.empty': 'ยังไม่มีข้อมูลนักวิจัย',
    'researchers.scholar': 'ดูผลงานวิจัยบน Google Scholar',
    'contact.title': 'ติดต่อเรา',
    'contact.info': 'ข้อมูลการติดต่อ',
    'contact.website': 'เว็บไซต์สถาบัน',
    'contact.email': 'อีเมลสำหรับติดต่อ',
    'contact.address': 'ที่อยู่',
    'contact.address.line1': 'กลุ่มวิจัย AIO LAB, คณะวิศวกรรมศาสตร์ มหาวิทยาลัยอุบลราชธานี',
    'contact.address.line2': '85 ถ.สถลมาร์ค ต.เมืองศรีไค อ.วารินชำราบ จ.อุบลราชธานี 34190',
    'contact.form.name': 'ชื่อ-นามสกุล',
    'contact.form.email': 'อีเมลของคุณ',
    'contact.form.message': 'ข้อความที่ต้องการติดต่อ',
    'contact.form.send': 'ส่งข้อความ',
    'news.title': 'ข่าวสารและกิจกรรม',
    'news.subtitle': 'ติดตามความเคลื่อนไหว กิจกรรม และประกาศล่าสุดจาก AIO LAB',
    'news.loading': 'กำลังโหลดข่าวสาร...',
    'news.empty': 'ยังไม่มีข่าวสารในขณะนี้',
    'news.back': '← กลับไปหน้าข่าวสาร',
    'news.readmore': 'อ่านเพิ่มเติม',
    'about.title': 'เกี่ยวกับ AIOLAB',
    'about.desc': 'AIOLAB เป็นศูนย์กลางการวิจัยและนวัตกรรมที่รวมผู้เชี่ยวชาญจากหลากหลายศาสตร์ เพื่อพัฒนาเทคโนโลยี AI, Machine Learning, Deep Learning, Optimization Algorithms และ Intelligent Systems สำหรับการประยุกต์ใช้งานจริงในภาคอุตสาหกรรมและสังคม',
    'director.role': 'Lab Director',
    'director.name': 'Professor Dr. Rapeepan Pitakaso',
    'director.title': 'Lab Director / Principal Investigator',
    'director.expertise': 'ผู้เชี่ยวชาญด้าน:',
    'director.expertise.1': 'Artificial Intelligence',
    'director.expertise.2': 'Metaheuristic Optimization',
    'director.expertise.3': 'Machine Learning',
    'director.expertise.4': 'Deep Learning',
    'director.expertise.5': 'Smart Decision Systems',
    'director.expertise.6': 'Operations Research',
    'vision.title': 'Vision',
    'vision.desc': 'เป็นห้องปฏิบัติการวิจัย AI ชั้นนำของประเทศไทย ที่สร้างนวัตกรรมเพื่อแก้ไขปัญหาจริงของสังคม อุตสาหกรรม และมนุษยชาติ',
    'mission.title': 'Mission',
    'mission.1': 'พัฒนาองค์ความรู้ด้าน AI และ Optimization ระดับแนวหน้า',
    'mission.2': 'ผลักดันงานวิจัยสู่การใช้งานจริง',
    'mission.3': 'สร้างบุคลากรด้าน AI คุณภาพสูง',
    'mission.4': 'สร้างเครือข่ายวิจัยทั้งในและต่างประเทศ',
    'mission.5': 'ส่งเสริมการใช้ AI อย่างมีจริยธรรมและยั่งยืน',
    'domains.title': 'Research Domains',
    'domains.subtitle': 'AIOLAB ดำเนินงานวิจัยครอบคลุมหลายสาขา เพื่อประยุกต์ใช้ในการแก้ปัญหาจริง',
    'domain.1.title': 'AI for Healthcare & Public Health',
    'domain.1.desc': 'การประยุกต์ AI เพื่อช่วยแพทย์ บุคลากรทางการแพทย์ และระบบสาธารณสุข',
    'domain.1.bullet.1': 'วิเคราะห์ภาพ X-ray / CT / MRI',
    'domain.1.bullet.2': 'AI-assisted diagnosis & Disease prediction',
    'domain.1.bullet.3': 'Musya AI (มัสยา AI): แพลตฟอร์มสนับสนุนงานด้านสุขภาพ ร่วมพัฒนากับ สสส.',
    'domain.2.title': 'AI for Agriculture & Smart Farming',
    'domain.2.desc': 'การใช้ AI และ IoT เพื่อเพิ่มผลผลิตและลดต้นทุน',
    'domain.2.bullet.1': 'Smart Greenhouse & Precision Agriculture',
    'domain.2.bullet.2': 'Yield Prediction & Disease Detection',
    'domain.2.bullet.3': 'พืชเป้าหมาย: Strawberry, Cannabis, Centella Asiatica ฯลฯ',
    'domain.3.title': 'AI for Aquaculture & Fisheries',
    'domain.3.desc': 'วิจัย AI เพื่อการเพาะเลี้ยงสัตว์น้ำอย่างแม่นยำ',
    'domain.3.bullet.1': 'Nile Tilapia / Shrimp Farming Optimization',
    'domain.3.bullet.2': 'Fish Disease Detection & Water Quality Monitoring',
    'domain.3.bullet.3': 'วิเคราะห์ DO, pH, Temperature แบบเรียลไทม์',
    'domain.4.title': 'AI for Education',
    'domain.4.desc': 'การประยุกต์ AI ในการเรียนรู้',
    'domain.4.bullet.1': 'Intelligent Tutoring Systems',
    'domain.4.bullet.2': 'Learning Analytics & Personalized Learning',
    'domain.4.bullet.3': 'AI Teaching Assistants',
    'domain.5.title': 'AI for Statistics & Data Analytics',
    'domain.5.desc': 'การวิเคราะห์ข้อมูลขั้นสูง (Advanced Analytics)',
    'domain.5.bullet.1': 'Predictive Analytics & Statistical Modeling',
    'domain.5.bullet.2': 'Time Series Forecasting & Data Mining',
    'domain.5.bullet.3': 'Business Intelligence',
    'domain.6.title': 'AI for Logistics & Supply Chain',
    'domain.6.desc': 'AI เพื่อแก้ปัญหาโลจิสติกส์',
    'domain.6.bullet.1': 'Vehicle Routing & Warehouse Optimization',
    'domain.6.bullet.2': 'Cross-border Logistics',
    'domain.6.bullet.3': 'Inventory Planning',
    'domain.7.title': 'AI for Tourism, Economy & Society',
    'domain.7.desc': 'การประยุกต์ AI ในการพัฒนาเศรษฐกิจและสังคม เช่น Smart Tourism, Demand Forecasting และ Export Analytics',
    'tech.title': 'Core Technologies',
    'tech.subtitle': 'เทคโนโลยีหลักที่ AIOLAB เชี่ยวชาญ',
    'tech.1': 'Artificial Intelligence',
    'tech.2': 'Machine Learning',
    'tech.3': 'Deep Learning',
    'tech.4': 'Generative AI',
    'tech.5': 'Reinforcement Learning',
    'tech.6': 'Optimization',
    'tech.7': 'Genetic Algorithms',
    'tech.8': 'IoT & Edge AI',
    'tech.9': 'Digital Twin',
    'innovations.title': 'Signature Innovations',
    'inno.1.title': 'AMIS (Artificial Multiple Intelligence System)',
    'inno.1.desc': 'อัลกอริทึม Optimization ขั้นสูงที่พัฒนาโดยทีมวิจัย AIOLAB',
    'inno.2.title': 'DM-VaNSAS',
    'inno.2.desc': 'Decision Making Variable Neighborhood Strategy Adaptive Search สำหรับแก้ปัญหาซับซ้อน',
    'inno.3.title': 'Musya AI',
    'inno.3.desc': 'AI Platform for Intelligent Health Solutions',
    'stats.1.value': '300+',
    'stats.1.label': 'Training Courses',
    'stats.1.desc': 'ให้บริการอบรมด้าน AI มากว่า 300 คอร์สทั่วประเทศ',
    'stats.2.value': '100+',
    'stats.2.label': 'Research Projects',
    'stats.2.desc': 'ความร่วมมือจากหลากหลายศาสตร์ทั่วประเทศ',
    'stats.3.value': '1000+',
    'stats.3.label': 'Trainees',
    'stats.3.desc': 'บุคลากรและนักศึกษาที่ผ่านการอบรมจาก AIOLAB',
    'responsible.title': 'Responsible AI',
    'responsible.desc': 'AIOLAB มุ่งมั่นพัฒนาเทคโนโลยีปัญญาประดิษฐ์อย่างมีจริยธรรม โดยยึดหลักการดังต่อไปนี้',
    'responsible.1': 'Transparency',
    'responsible.2': 'Fairness',
    'responsible.3': 'Explainability',
    'responsible.4': 'Privacy Protection',
    'responsible.5': 'Human-centered',
    'admin.login.title': 'เข้าสู่ระบบ Admin',
    'admin.login.password': 'รหัสผ่าน',
    'admin.login.placeholder': 'ใส่รหัสผ่าน...',
    'admin.login.button': 'เข้าสู่ระบบ',
    'footer.copyright': '© 2026 กลุ่มวิจัย AIO LAB มหาวิทยาลัยอุบลราชธานี สงวนลิขสิทธิ์',
  },
  en: {
    'nav.home': 'Home',
    'nav.researchers': 'Researchers',
    'nav.news': 'News',
    'nav.contact': 'Contact Us',
    'nav.admin': 'Admin Login',
    'hero.title': 'Innovation. Research. Discovery.',
    'hero.subtitle': 'Welcome to the AIO LAB research group at Ubon Ratchathani University. We are committed to developing new research and innovations to advance scientific and technological knowledge for society.',
    'hero.btn.researchers': 'Meet Our Researchers',
    'hero.btn.news': 'News & Events',
    'researchers.title': 'Our Researchers',
    'researchers.subtitle': 'Get to know the personnel and research team of AIO LAB, Ubon Ratchathani University',
    'researchers.loading': 'Loading data...',
    'researchers.empty': 'No researchers found',
    'researchers.scholar': 'View research on Google Scholar',
    'contact.title': 'Contact Us',
    'contact.info': 'Contact Information',
    'contact.website': 'Institute Website',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.address.line1': 'AIO LAB Research Group, Faculty of Engineering, Ubon Ratchathani University',
    'contact.address.line2': '85 Sathonmark Rd., Mueang Si Khai, Warin Chamrap, Ubon Ratchathani 34190',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Your Email',
    'contact.form.message': 'Your Message',
    'contact.form.send': 'Send Message',
    'news.title': 'News & Events',
    'news.subtitle': 'Follow the latest updates, events, and announcements from AIO LAB.',
    'news.loading': 'Loading news...',
    'news.empty': 'No news found.',
    'news.back': '← Back to news',
    'news.readmore': 'Read more',
    'about.title': 'About AIOLAB',
    'about.desc': 'AIOLAB is a research and innovation hub that brings together experts from various disciplines to develop AI, Machine Learning, Deep Learning, Optimization Algorithms, and Intelligent Systems for real-world applications in industry and society.',
    'director.role': 'Lab Director',
    'director.name': 'Professor Dr. Rapeepan Pitakaso',
    'director.title': 'Lab Director / Principal Investigator',
    'director.expertise': 'Expertise:',
    'director.expertise.1': 'Artificial Intelligence',
    'director.expertise.2': 'Metaheuristic Optimization',
    'director.expertise.3': 'Machine Learning',
    'director.expertise.4': 'Deep Learning',
    'director.expertise.5': 'Smart Decision Systems',
    'director.expertise.6': 'Operations Research',
    'vision.title': 'Vision',
    'vision.desc': 'To be the leading AI research laboratory in Thailand, creating innovations to solve real-world problems for society, industry, and humanity.',
    'mission.title': 'Mission',
    'mission.1': 'Advance cutting-edge knowledge in AI and Optimization.',
    'mission.2': 'Push research towards practical applications.',
    'mission.3': 'Produce high-quality AI personnel.',
    'mission.4': 'Build domestic and international research networks.',
    'mission.5': 'Promote the ethical and sustainable use of AI.',
    'domains.title': 'Research Domains',
    'domains.subtitle': 'AIOLAB conducts research across various fields for real-world problem solving.',
    'domain.1.title': 'AI for Healthcare & Public Health',
    'domain.1.desc': 'Applying AI to assist doctors, medical personnel, and the public health system.',
    'domain.1.bullet.1': 'X-ray / CT / MRI image analysis',
    'domain.1.bullet.2': 'AI-assisted diagnosis & Disease prediction',
    'domain.1.bullet.3': 'Musya AI: Health support platform co-developed with ThaiHealth',
    'domain.2.title': 'AI for Agriculture & Smart Farming',
    'domain.2.desc': 'Using AI and IoT to increase yield and reduce costs.',
    'domain.2.bullet.1': 'Smart Greenhouse & Precision Agriculture',
    'domain.2.bullet.2': 'Yield Prediction & Disease Detection',
    'domain.2.bullet.3': 'Target crops: Strawberry, Cannabis, Centella Asiatica, etc.',
    'domain.3.title': 'AI for Aquaculture & Fisheries',
    'domain.3.desc': 'AI research for precision aquaculture.',
    'domain.3.bullet.1': 'Nile Tilapia / Shrimp Farming Optimization',
    'domain.3.bullet.2': 'Fish Disease Detection & Water Quality Monitoring',
    'domain.3.bullet.3': 'Real-time DO, pH, Temperature analysis',
    'domain.4.title': 'AI for Education',
    'domain.4.desc': 'Applying AI in learning.',
    'domain.4.bullet.1': 'Intelligent Tutoring Systems',
    'domain.4.bullet.2': 'Learning Analytics & Personalized Learning',
    'domain.4.bullet.3': 'AI Teaching Assistants',
    'domain.5.title': 'AI for Statistics & Data Analytics',
    'domain.5.desc': 'Advanced Analytics.',
    'domain.5.bullet.1': 'Predictive Analytics & Statistical Modeling',
    'domain.5.bullet.2': 'Time Series Forecasting & Data Mining',
    'domain.5.bullet.3': 'Business Intelligence',
    'domain.6.title': 'AI for Logistics & Supply Chain',
    'domain.6.desc': 'AI for solving logistics problems.',
    'domain.6.bullet.1': 'Vehicle Routing & Warehouse Optimization',
    'domain.6.bullet.2': 'Cross-border Logistics',
    'domain.6.bullet.3': 'Inventory Planning',
    'domain.7.title': 'AI for Tourism, Economy & Society',
    'domain.7.desc': 'Applying AI for socio-economic development, such as Smart Tourism, Demand Forecasting, and Export Analytics.',
    'tech.title': 'Core Technologies',
    'tech.subtitle': 'Core technologies that AIOLAB specializes in',
    'tech.1': 'Artificial Intelligence',
    'tech.2': 'Machine Learning',
    'tech.3': 'Deep Learning',
    'tech.4': 'Generative AI',
    'tech.5': 'Reinforcement Learning',
    'tech.6': 'Optimization',
    'tech.7': 'Genetic Algorithms',
    'tech.8': 'IoT & Edge AI',
    'tech.9': 'Digital Twin',
    'innovations.title': 'Signature Innovations',
    'inno.1.title': 'AMIS (Artificial Multiple Intelligence System)',
    'inno.1.desc': 'Advanced Optimization algorithm developed by the AIOLAB research team.',
    'inno.2.title': 'DM-VaNSAS',
    'inno.2.desc': 'Decision Making Variable Neighborhood Strategy Adaptive Search for solving complex problems.',
    'inno.3.title': 'Musya AI',
    'inno.3.desc': 'AI Platform for Intelligent Health Solutions.',
    'stats.1.value': '300+',
    'stats.1.label': 'Training Courses',
    'stats.1.desc': 'Provided over 300 AI training courses nationwide.',
    'stats.2.value': '100+',
    'stats.2.label': 'Research Projects',
    'stats.2.desc': 'Collaborations across various disciplines nationwide.',
    'stats.3.value': '1000+',
    'stats.3.label': 'Trainees',
    'stats.3.desc': 'Personnel and students trained by AIOLAB.',
    'responsible.title': 'Responsible AI',
    'responsible.desc': 'AIOLAB is committed to developing artificial intelligence technologies ethically, adhering to the following principles:',
    'responsible.1': 'Transparency',
    'responsible.2': 'Fairness',
    'responsible.3': 'Explainability',
    'responsible.4': 'Privacy Protection',
    'responsible.5': 'Human-centered',
    'admin.login.title': 'Admin Login',
    'admin.login.password': 'Password',
    'admin.login.placeholder': 'Enter password...',
    'admin.login.button': 'Login',
    'footer.copyright': '© 2026 AIO LAB Research Group, Ubon Ratchathani University. All rights reserved.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('th');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const savedLang = localStorage.getItem('aio_lang') as Language;
    if (savedLang && (savedLang === 'th' || savedLang === 'en')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('aio_lang', lang);
  };

  const t = (key: string): string => {
    // Avoid hydration mismatch by using TH default before mount if needed
    // But practically, returning the translation string is fine since it's a client component
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div className={!mounted ? 'invisible' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
